ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE approved_officers DISABLE ROW LEVEL SECURITY;
ALTER TABLE cameras DISABLE ROW LEVEL SECURITY;
ALTER TABLE criminals DISABLE ROW LEVEL SECURITY;
